// High-visibility stimulus 1
const STIM_HV1 = {
  stimulus_id: "HV1",
  visibility: "high",
  title: "High Visibility 1",
  source: "Brambach",
  en: `Wallfried Känsterle, the simple locksmith, sits in front of the television after work. Where else? The evening news, the weather map; the weightlifting championship interests Känsterle. “Turn the sound down, the boys are sleeping!” calls Rosa, who has been washing dishes in the kitchen and now comes in. Känsterle obeys.
“It’s cold outside,” she chatters, “how good that we have storm windows. Only they really ought to be freshly painted again. Wallfried, in the spring you absolutely have to paint the storm windows. And they need to be puttied too! The putty is crumbling everywhere. No one in the building has such shabby storm windows as we do! I get annoyed every time I clean the storm windows. Did you hear?” “Yes, yes,” says Känsterle absentmindedly. “What is he doing there?” asks Rosa, pointing at the television screen. “He could use his strength for something better! Turn that off, I have to talk to you!” “In a minute, in a minute!” says Känsterle and bends a little closer to the screen. “Mr. Hansmann downstairs on the ground floor re-puttied and painted his storm windows last summer, although it wasn’t even necessary. Take Mr. Hansmann as an example! He gave his entire vacation to it. Such an orderly man... The day after tomorrow is St. Nicholas Day. Do you remember Mr. Weckhammer? I ran into his wife today at the co-op, all in black. Old Weckhammer collapsed while climbing the stairs, heart attack.” Känsterle presses the “Off” button.
“One consolation,” Rosa begins again, “is that the Weckhammer children are out of the worst of it. The widow asked whether we could use the St. Nicholas costume. A robe with rabbit fur at the collar, a beautiful white beard, boots, sack, and crozier, all in good condition. She only wants forty marks for it, she said. My husband will come and fetch it, I told her. Isn’t that right, Wallfried, you’ll give Paul and little Konrad this pleasure?” Känsterle looks at the dull screen. “Wallfried!” Rosa calls. “But Rosa,” Känsterle murmurs helplessly, “you know I’m not cut out for something like that. What am I supposed to say to the boys? A St. Nicholas has to be a practiced speaker! Has to speak well and at length...”
Rosa smooths the tablecloth with her hand and shakes her head; her bun, despite the comb that holds it fast like a brown set of teeth, wobbles obstinately. “You cursed stockfish!” she hisses. “You won’t even give your own boys this pleasure! And I’ve already bought nuts, dates, figs, a few oranges, and everything at the co-op!”
Känsterle’s spirits darken. He thinks of the heavy office forced upon him. A dusty lightbulb casts murky light. Känsterle stands in the attic; he hesitantly transforms himself into Father Christmas. The robe that had once so splendidly clothed the hundred-kilo Weckhammer is far too roomy for the squat Känsterle. He glues the beard to his ears. His gaze brushes over the boots, and as it does so he tries to remember Weckhammer’s feet. He crumples up a few newspapers and stuffs them into the stone-hard tubs. Although he is wearing two pairs of coarse woolen socks, he still cannot find a proper foothold. He pulls the hood over his head, swings the full sack over his shoulder, and takes hold of the crozier.
The descent begins. Slowly the hood slips down over his forehead and eyes; the beard shifts upward and tickles his nose. Känsterle searches with his left foot for the next stair and steps on the hem of the robe. He bends his upper body forward and tries to move his right foot ahead; as he does so, the heavy sack rolls forward from his shoulder, and man and sack go tumbling into the depths. A dull thud. There is a trilling in Känsterle’s ears. A lump of plaster falls from the wall.
“Oh! Surely St. Nicholas has knocked!” Rosa’s voice sounds from behind the door. She opens it and says: “My God... what are you doing on the floor? Straighten your beard, the children are coming!” Känsterle pulls himself up by the banister and stands there unsteadily. Then he winds up and gives Rosa a slap across the face. Rosa howls, staggers back; Känsterle stamps into the living room, tears Rosa’s favorite piece, a porcelain peacock, from the chest of drawers and knocks its head off against the edge. Then he grabs the china cabinet; he shakes it until shards hail down from the compartments. Then the rubber plant, pot and all, flies through a window and a storm window; outside, it crashes onto the street. “He’s slaughtering the boys!” Rosa shrieks through the stairwell. Doors open on every floor. A wild rush upstairs. People gather around Rosa, who stands dumbfounded against the wall and points into the open apartment. Mr. Hansmann is the first to venture into the room, looks over the destruction; a glint comes into his eyes, and he says: “My dear Känsterle, is that all?” Miserably, Father Christmas squats in the armchair, while Paul and little Konrad crawl out from under the sofa. A cold wind blows through the room.`,
  de: `Wallfried Känsterle, der einfache Schlosser, sitzt nach Feierabend vor dem Fernsehschirm. Wo denn sonst? - Tagesschau, Wetterkarte; die Meisterschaft der Gewichtheber interessiert Känsterle. „Mach den Ton leiser, die Buben schlafen!“ ruft Rosa, die in der Küche Geschirr gespült hat und nun hereinkommt. Känsterle gehorcht.
„Es ist kalt draußen“, plaudert sie, „wie gut, dass wir Winterfenster haben. Nur frisch anstreichen sollte man sie wieder einmal. Wallfried, im Frühjahr musst du unbedingt die Winterfenster streichen. Und kitten muss man sie! Überall bröckelt der Kitt. Niemand im Haus hat so schäbige Winterfenster wie wir! Ich ärgere mich jedes Mal, wenn ich die Winterfenster putze. Hast du gehört?“ „Ja, ja“, sagt Känsterle abwesend. „Was macht denn der da?“ fragt Rosa und deutet auf den Fernsehschirm. „Der könnte seine Kraft auch für was Besseres gebrauchen! Stell das doch ab, ich hab mit dir zu reden!“ „Gleich, gleich!“ sagt Känsterle und beugt sich etwas näher zum Schirm. „Herr Hansmann im Parterre hat im letzten Sommer seine Winterfenster neu gekittet und gestrichen, obwohl es gar nicht nötig war. Nimm dir mal ein Beispiel an Herrn Hansmann! Seine ganzen Ferien hat er dran gegeben. So ein ordentlicher Mann... Übermorgen ist Sankt Nikolaus. Erinnerst du dich an Herrn Weckhammer? Ich hab heut im Konsum seine Frau getroffen, ganz in Schwarz. Der alte Weckhammer ist umgefallen, beim Treppensteigen, Herzschlag.“ Känsterle drückt auf die Taste „Aus“.
„Ein Trost“, fängt Rosa wieder an, „dass die Weckhammerschen Kinder aus dem Gröbsten raus sind.“ Die Witwe fragt, ob wir den Nikolaus gebrauchen könnten. Eine Kutte mit Kaninchenfell am Kragen, schöner weißer Bart, Stiefel, Sack und Krummstab, alles gut erhalten. Nur vierzig Mark will sie dafür, hat sie gesagt. Mein Mann wird kommen und ihn holen, hab ich da gesagt. Nicht wahr. Wallfried, du wirst Paul und Konradle die Freude machen?“ Känsterle schaut auf die matte Scheibe. „Wallfried!“ ruft Rosa. „Aber Rosa“, murmelt Känsterle hilflos, „du weißt doch, dass ich nicht zu so was tauge. Was soll ich denn den Buben sagen? Ein Nikolaus muss ein geübter Redner sein! Muss gut und viel sprechen...“
Rosa glättet mit der Hand das Tischtuch und schüttelt den Kopf, wobei der Haarknoten, trotz des Kamms, der ihn wie ein braunes Gebiss festhält, eigensinnig wackelt. „Vermaledeiter Stockfisch!“ zischt sie. „Nicht einmal den eignen Buben willst du diese Freude machen! Dabei hab ich schon im Konsum Nüsse, Datteln, Feigen, ein paar Apfelsinen und alles eingekauft!“
Känsterles Gemüt verdüstert sich. Er denkt an das schwere, ihm aufgezwungene Amt. Eine verstaubte Glühbirne wirft trübes Licht. Känsterle steht auf dem Dachboden; er verwandelt sich zögernd in einen Weihnachtsmann. Die Kutte, die den Hundertkilomann Weckhammer einst so prächtig gekleidet hat, ist dem gedrungenen Känsterle viel zu geräumig. Er klebt den Bart an die Ohren. Sein Blick streift die Stiefel, und dabei versucht er sich an die Füße Weckhammers zu erinnern. Er zerknüllt ein paar Zeitungen und stopft sie in die steinharten Bottiche. Obwohl er zwei Paar grobwollene Socken anhat, findet er noch immer keinen rechten Halt. Er zieht die Kapuze über den Kopf, schwingt den vollen Sack über die Schulter und ergreift den Krummstab.
Der Abstieg beginnt. Langsam rutscht ihm die Kapuze über Stirn und Augen; der Bart verschiebt sich nach oben und kitzelt seine Nase. Känsterle sucht mit dem linken Fuß die nächste Treppenstufe und tritt auf den Kuttensaum. Er beugt den Oberkörper vor und will den rechten Fuß vorsetzen; dabei rollt der schwere Sack von der Schulter nach vorn, Mann und Sack rumpeln in die Tiefe. Ein dumpfer Schlag. In Känsterles Ohren trillert es. Ein Gipsfladen fällt von der Wand.
„Oh! Jetzt hat sicher der Nikolaus angeklopft!“ tönt Rosas Stimme hinter der Tür. Sie öffnet und sagt: „Mein Gott... was machst du denn da am Boden? Zieh den Bart zurecht, die Kinder kommen!“ Känsterle zieht sich am Treppengeländer hoch, steht unsicher da. Dann holt er aus und versetzt Rosa eine Backpfeife. Rosa heult auf, taumelt zurück; Känsterle stampft ins Wohnzimmer, reißt Rosas Lieblingsstück, einen Porzellanpfauen, von der Kommode und schlägt ihm an der Kante den Kopf ab. Dann packt er den Geschirrschrank; er schüttelt ihn, bis die Scherben aus den Fächern hageln. Dann fliegt der Gummibaum samt Topf durch ein Fenster und ein Winterfenster; auf der Straße knallt es. „Er schlachtet die Buben ab!“ kreischt Rosa durchs Treppenhaus. Auf allen Stockwerken öffnen sich Türen. Ein wildes Gerenne nach oben. Man versammelt sich um Rosa, die verdattert an der Wand steht und in die offene Wohnung zeigt. Als erster wagt sich Herr Hansmann in die Stube, betrachtet die Zerstörungen; ein Glitzern kommt in seine Augen, und er sagt: „Mein lieber Känsterle, ist das alles?“ Elend hockt der Weihnachtsmann im Sessel, während Paul und Konradle unter dem Sofa hervorkriechen. Ein kalter Wind zieht durch die Stube.`
};
